import { OBJECT_EFFECTS, OBJECT_EFFECT_META } from 'model/effect';
import { OBJECT_PROPERTIES, OBJECT_PROPERTY_META } from 'model/property';

export const OBJECT_META = {
  RECT: 'rect',
  CIRCLE: 'circle',
  ICON: 'icon',
  LINE: 'line',
} as const;

export const OBJECT_SUPPORTED_PROPERTIES: {
  [key in OBJECT_TYPES]: readonly OBJECT_PROPERTIES[];
} = {
  [OBJECT_META.RECT]: [
    OBJECT_PROPERTY_META.TEXT,
    OBJECT_PROPERTY_META.RECT,
    OBJECT_PROPERTY_META.FILL,
    OBJECT_PROPERTY_META.STROKE,
    OBJECT_PROPERTY_META.ROTATE,
    OBJECT_PROPERTY_META.SCALE,
    OBJECT_PROPERTY_META.FADE,
  ],
  [OBJECT_META.CIRCLE]: [
    OBJECT_PROPERTY_META.TEXT,
    OBJECT_PROPERTY_META.RECT,
    OBJECT_PROPERTY_META.FILL,
    OBJECT_PROPERTY_META.STROKE,
    OBJECT_PROPERTY_META.ROTATE,
    OBJECT_PROPERTY_META.SCALE,
    OBJECT_PROPERTY_META.FADE,
  ],
  [OBJECT_META.ICON]: [
    OBJECT_PROPERTY_META.TEXT,
    OBJECT_PROPERTY_META.RECT,
    OBJECT_PROPERTY_META.FILL,
    OBJECT_PROPERTY_META.ROTATE,
    OBJECT_PROPERTY_META.SCALE,
    OBJECT_PROPERTY_META.FADE,
  ],
  [OBJECT_META.LINE]: [
    OBJECT_PROPERTY_META.TEXT,
    OBJECT_PROPERTY_META.RECT,
    OBJECT_PROPERTY_META.STROKE,
    OBJECT_PROPERTY_META.ROTATE,
    OBJECT_PROPERTY_META.SCALE,
    OBJECT_PROPERTY_META.FADE,
  ],
} as const;

export const OBJECT_SUPPORTED_EFFECTS: {
  [key in OBJECT_TYPES]: readonly OBJECT_EFFECTS[];
} = {
  [OBJECT_META.RECT]: [
    OBJECT_EFFECT_META.CREATE,
    OBJECT_EFFECT_META.REMOVE,
    OBJECT_EFFECT_META.FADE,
    OBJECT_EFFECT_META.FILL,
    OBJECT_EFFECT_META.STROKE,
    OBJECT_EFFECT_META.ROTATE,
    OBJECT_EFFECT_META.SCALE,
    OBJECT_EFFECT_META.RECT,
  ],
  [OBJECT_META.CIRCLE]: [
    OBJECT_EFFECT_META.CREATE,
    OBJECT_EFFECT_META.REMOVE,
    OBJECT_EFFECT_META.FADE,
    OBJECT_EFFECT_META.FILL,
    OBJECT_EFFECT_META.STROKE,
    OBJECT_EFFECT_META.ROTATE,
    OBJECT_EFFECT_META.SCALE,
    OBJECT_EFFECT_META.RECT,
  ],
  [OBJECT_META.ICON]: [
    OBJECT_EFFECT_META.CREATE,
    OBJECT_EFFECT_META.REMOVE,
    OBJECT_EFFECT_META.FADE,
    OBJECT_EFFECT_META.FILL,
    OBJECT_EFFECT_META.ROTATE,
    OBJECT_EFFECT_META.SCALE,
    OBJECT_EFFECT_META.RECT,
  ],
  [OBJECT_META.LINE]: [
    OBJECT_EFFECT_META.CREATE,
    OBJECT_EFFECT_META.REMOVE,
    OBJECT_EFFECT_META.FADE,
    OBJECT_EFFECT_META.STROKE,
    OBJECT_EFFECT_META.ROTATE,
    OBJECT_EFFECT_META.SCALE,
    OBJECT_EFFECT_META.RECT,
  ],
} as const;

export const OBJECT_ADDABLE_EFFECTS: {
  [key in OBJECT_TYPES]: readonly OBJECT_EFFECTS[];
} = {
  [OBJECT_META.RECT]: [
    OBJECT_EFFECT_META.FADE,
    OBJECT_EFFECT_META.FILL,
    OBJECT_EFFECT_META.STROKE,
    OBJECT_EFFECT_META.ROTATE,
    OBJECT_EFFECT_META.SCALE,
    OBJECT_EFFECT_META.RECT,
  ],
  [OBJECT_META.CIRCLE]: [
    OBJECT_EFFECT_META.FADE,
    OBJECT_EFFECT_META.FILL,
    OBJECT_EFFECT_META.STROKE,
    OBJECT_EFFECT_META.ROTATE,
    OBJECT_EFFECT_META.SCALE,
    OBJECT_EFFECT_META.RECT,
  ],
  [OBJECT_META.ICON]: [
    OBJECT_EFFECT_META.FADE,
    OBJECT_EFFECT_META.FILL,
    OBJECT_EFFECT_META.ROTATE,
    OBJECT_EFFECT_META.SCALE,
    OBJECT_EFFECT_META.RECT,
  ],
  [OBJECT_META.LINE]: [
    OBJECT_EFFECT_META.FADE,
    OBJECT_EFFECT_META.STROKE,
    OBJECT_EFFECT_META.ROTATE,
    OBJECT_EFFECT_META.SCALE,
    OBJECT_EFFECT_META.RECT,
  ],
} as const;

export type OBJECT_TYPES = typeof OBJECT_META[keyof typeof OBJECT_META];
